### ISSUE TITLE
Bug: Missing Stylesheet

### ISSUE THREAD

**Issue by brimwats** [eth-p/obsidian-callout-manager#4]
This plugin takes a long time to load. Did some digging and it's because of this I think

```
plugin:callout-manager:1620 Unable to fetch Obsidian stylesheet. Error: [obsidian-extra]: Obsidian 1.2.2 has not been tested with this function
    at eval (plugin:callout-manager:154:13)
    at Generator.next (<anonymous>)
    at eval (plugin:callout-manager:147:67)
    at new Promise (<anonymous>)
    at __awaiter (plugin:callout-manager:129:10)
    at fetchObsidianStyles (plugin:callout-manager:152:10)
    at StylesheetWatcher.checkForChangesObsidian (plugin:callout-manager:1612:35)
    at StylesheetWatcher.checkForChanges (plugin:callout-manager:1594:28)
    at StylesheetWatcher.watch (plugin:callout-manager:1531:10)
    at eval (plugin:callout-manager:2983:37)

```

**Comment by eth-p** [comment]
That message is shown when using newer Obsidian versions than I tested, since I use some undocumented functions that might break between releases. I haven't had the chance to finish my upcoming changes, but that message will be permanently fixed with the next release :)

In either case, though, it shouldn't affect startup time. What OS are you running Obsidian on?

**Comment by rokville** [comment]
I haven't opened the dev console in a while, but, as an fyi, this is still an issue.
I'm running MacOS 14.2.1 (Sonoma)



```
plugin:callout-manager:1620 Unable to fetch Obsidian stylesheet. Error: [obsidian-extra]: Obsidian 1.5.3 has not been tested with this function
    at eval (plugin:callout-manager:154:13)
    at Generator.next (<anonymous>)
    at eval (plugin:callout-manager:147:67)
    at new Promise (<anonymous>)
    at __awaiter (plugin:callout-manager:129:10)
    at fetchObsidianStyles (plugin:callout-manager:152:10)
    at StylesheetWatcher.checkForChangesObsidian (plugin:callout-manager:1612:35)
    at StylesheetWatcher.checkForChanges (plugin:callout-manager:1594:28)
    at StylesheetWatcher.watch (plugin:callout-manager:1531:10)
    at eval (plugin:callout-manager:2983:37)


```

**Comment by eth-p** [comment]
As of version 1.1.0, this should no longer happen :)
